version: '3'
services:
    mysql:
        image: mysql:5.7
        volumes:
            - mysql-data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root

    php:
        build:
          context: ./
        volumes:
            - ./:/var/www/html
        ports:
            - "80:80"
        links:
            - mysql
        depends_on:
            - mysql

volumes:
    mysql-data:
